# Generated by Django 5.2.14 on 2026-07-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('email',models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=15)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
