# Generated by Django 5.2.14 on 2026-07-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseusers', '0003_alter_user_options_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('merchant', 'Merchant')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('working', 'Working'), ('gamer', 'Gamer'), ('enthusiast', 'Enthusiast')], max_length=20, null=True),
        ),
    ]
