# Generated by Django 5.2.14 on 2026-08-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseusers', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('merchant', 'Merchant')], default='merchant', max_length=20),
        ),
    ]
