# Generated by Django 5.2.14 on 2026-08-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseusers', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('merchant', 'Merchant')], default='user', max_length=20),
        ),
    ]
