# Generated by Django 5.2.14 on 2026-08-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseusers', '0009_alter_user_date_joined_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('merchant', 'Merchant'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
