# Generated by Django 5.2.14 on 2026-09-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseusers', '0011_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
