# Generated by Django 5.2.14 on 2026-08-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_for',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('working', 'Working'), ('gamer', 'Gamer'), ('enthusiast', 'Enthusiast')], max_length=20, null=True),
        ),
    ]
