# Generated by Django 5.2.14 on 2026-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_product_recommended_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GPU', 'Graphics Card'), ('CPU', 'Processor'), ('MB', 'Motherboard'), ('RAM', 'Memory'), ('SSD', 'SSD Storage'), ('HDD', 'HDD Storage'), ('PSU', 'Power Supply'), ('CASE', 'Case'), ('COOL', 'Cooling'), ('PERI', 'Peripherals'), ('MON', 'Monitor'), ('LAP', 'Laptop'), ('SRVR', 'Server')], max_length=10),
        ),
    ]
