# Generated by Django 5.2.14 on 2026-08-08 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recommended_for',
        ),
        migrations.AddField(
            model_name='product',
            name='pointsbalance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('recommended_for', models.CharField(blank=True, choices=[('student', 'Student'), ('working', 'Working'), ('gamer', 'Gamer'), ('enthusiast', 'Enthusiast')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
