# Generated by Django 5.2.14 on 2026-08-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_pointsuser_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_for',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('working', 'Working Professional'), ('gamer', 'Gamer'), ('enthusiast', 'Enthusiast')], max_length=20, null=True),
        ),
    ]
