# Generated by Django 5.2.14 on 2026-08-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_product_recommended_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpoints',
            name='recommended_for',
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_for',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('working', 'Working'), ('gamer', 'Gamer'), ('enthusiast', 'Enthusiast')], max_length=20, null=True),
        ),
    ]
