# Generated by Django 5.2.14 on 2026-08-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_userpoints_recommended_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_for_display',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
