# Generated by Django 5.2.14 on 2026-08-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_product_recommended_for_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recommended_for_display',
        ),
    ]
