# Generated by Django 5.2.14 on 2026-08-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_product_recommended_for_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
