# Generated by Django 5.2.14 on 2026-08-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recommended_for_display',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
