# Generated by Django 5.2.14 on 2026-08-14 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_product_recommended_for_display_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsuser',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_user', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='pointsuser',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.product'),
        ),
        migrations.AddField(
            model_name='pointsuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='product_cat',
            field=models.CharField(blank=True, choices=[('DC', 'Discount'), ('PRE-SALE', 'Pre-Sales'), ('NR', 'New Release')], max_length=20, null=True),
        ),
    ]
