# Generated by Django 5.2.14 on 2026-08-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_pointsuser_cart_pointsuser_product_pointsuser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
