# Generated by Django 5.2.14 on 2026-08-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_product_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
