# Generated by Django 5.2.14 on 2026-08-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_product_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.CharField(blank=True, choices=[('Pasig Main', 'Pasig City Main Branch'), ('QC', 'Quezon City Branch'), ('MALABON', 'MALABON BRANCH'), ('PARAÑAQUE', 'PARAÑAQUE BRANCH'), ('TAGUIG', 'TAGUIG BRANCH'), ('PASAY', 'PASAY BRANCH'), ('CEBU', 'CEBU CITY BRANCH')], max_length=200),
        ),
    ]
