# Generated by Django 5.2.14 on 2026-08-17 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_rename_image_product_img1_product_img2_product_img3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware', models.CharField(max_length=300)),
                ('hardwarename', models.CharField(max_length=400)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='cart.product')),
            ],
            options={
                'unique_together': {('hardware', 'hardwarename')},
            },
        ),
    ]
