# Generated by Django 5.2.14 on 2026-08-18 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_productspecs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
    ]
