# Generated by Django 5.2.14 on 2026-08-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_remove_product_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('ASUS', 'ASUS'), ('LENOVO', 'LENOVO'), ('ACER', 'ACER'), ('HP', 'Hewlett Packard'), ('MSI', 'Micro Star International'), ('GOOGLE', 'GOOGLE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.CharField(blank=True, choices=[('INTL', 'INTEL'), ('AMD', 'Advance Micro Devices')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu',
            field=models.CharField(blank=True, choices=[('NVDA', 'NVIDIA'), ('AMDR', 'RADEON')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subbrand',
            field=models.CharField(blank=True, choices=[('ASUS', 'ASUS'), ('ROG', 'ROG'), ('HP', 'HP'), ('TUFF', 'TUFF'), ('PREDATOR', 'PREDATOR'), ('AERO', 'AERO'), ('AUROS', 'AUROS'), ('ALIENWARE', 'ALIENWARE'), ('ACER', 'ACER'), ('GOOGLE', 'GOOGLE'), ('GOOGLE', 'GOOGLE'), ('THINKPAD', 'THINKPAD'), ('YOGA', 'YOGA'), ('LOQ', 'LOQ'), ('THINKBOOK', 'THINKBOOK'), ('SLIMBOOK', 'SLIMBOOK'), ('XPS', 'XPS'), ('MACBOOK', 'MACBOOK'), ('ZENBOOK', 'ZENBOOK'), ('SPECTRE', 'SPECTRE'), ('SWIFT', 'SWIFT'), ('SURFACE', 'SURFACE'), ('SPIN', 'SPIN'), ('ENVY', 'ENVY'), ('FLEX', 'FLEX')], max_length=20, null=True),
        ),
    ]
