# Generated by Django 5.2.14 on 2026-08-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_product_brand_product_cpu_product_gpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='typeproduct',
            field=models.CharField(blank=True, choices=[('GL', 'Gaming Laptop'), ('CL', 'CHROMEBOOK LAPTOP'), ('WL', 'Working Laptop'), ('UL', 'UltraBook Laptop'), ('2IN1', '2in1 Laptop')], max_length=20, null=True),
        ),
    ]
